version: '3.8'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=admin
    command: >
      sh -c 'python manage.py wait_for_db && \
        python manage.py migrate && \
        python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db

  db:
    image: postgres:15.5-alpine3.19
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=admin

volumes:
  static-data:
  dev-db-data:
